# Values for the zenml helm chart

serviceAccount:
  create: false  # we already provision the service account with terraform
  name: "zenml"
  
database:
  external:
    type: mysql
    host: zenml-db.mysql.svc.cluster.local 
    port: 3306
    database: zenml
    username: "admin_user" 

  passwordSecretRef:
    # name we take from --set in terraform
    key: "password"
